Algoritmo "Entrada e Saida de Dado"
// Disciplina   : [Estrutura principal dos algoritmos]
// Professor   :  Cleison Melo
// Descrição   : Aqui vamos descreve sobre a entrada e saida de dado e sua funcao na programação
// Autor(a)    : Tiago Sebastian
// Data atual  : 15/09/2021
Var
// Seção de Declarações das variáveis 
    nome: caractere
    nota: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
     leia(nome)
     leia(nota)
Fimalgoritmo